### PR TITLE
Fn product copy - Don't merge

### PR DESCRIPTION
**Pull request by spykelionel**
Staging area for product page

### CODE REVIEW

**Comment by ClareJitu** [comment]
The 'Developer' in the navigation bar should be 'Documentation' instead.
Also, the 'more' in all sections should be alligned close to the end of the frames just above them.
Nice work tho

**Comment by tiana0803** [comment]
Documentation not Developer on the top Nav bar.
Supported language text is too black 
Search text and icon are different shades.
Icons are too large.
The space between the Nav bar and PRODUCT is too much
Screen Shot 2022-08-02 at 4 38 54 PM

ARTICLES & PLATFORM text are too black
same large icons
Body text should be regular not bold.
Screen Shot 2022-08-02 at 4 43 51 PM

**Comment by spykelionel** [comment]
@Codeyenum check the comments

**Review by ClareJitu — CHANGES_REQUESTED** [review]
The 'Developer' in the navigation bar should be 'Documentation' instead.
Also, the 'more' in all sections should be alligned close to the end of the frames just above them.
Nice work tho

**Comment by Codeyenum** [comment]
made suggested changes

**Comment by spykelionel** [comment]
Duplicate Pull request. Check #46

**Pull request closed without merging**
