### PR TITLE
Fn landing page

### PR DESCRIPTION
**Pull request by Lharbeeb**

### CODE REVIEW

**Review by tiana0803 — COMMENTED** [review]
The body text shouldn't be bold. Also the search icon and text are of different shades..
Screen Shot 2022-08-02 at 3 36 16 PM

The space between the heading and body text is way too much also make the body text regular not body. Then the Join the community button text shouldn't drop down.. 
Screen Shot 2022-08-02 at 3 41 10 PM

Please always check the designs on Figma to be sure

**Comment by tiana0803** [comment]
Please centralized the text in the buttons, also there is a missing text under join community..
Screen Shot 2022-08-02 at 3 46 44 PM

Spacing between them is much.....
Screen Shot 2022-08-02 at 3 49 19 PM

**Review by spykelionel — CHANGES_REQUESTED** [review]
.

**Review by ClareJitu — CHANGES_REQUESTED** [review]
Screenshot from 2022-08-03 18-43-02
-06c7-41f2-81cb-21fa9030b4ab.png)
The height of the text should be adjusted as speculated in the design

**Review by ClareJitu — CHANGES_REQUESTED** [review]
Screenshot from 2022-08-03 18-44-30
The rectangle has designs in the original design in figma

**Review by ClareJitu — CHANGES_REQUESTED** [review]
Screenshot from 2022-08-03 18-44-40
The text in the authenticated frame and unauthenticated frames should be up 
Also, the height of the button should be corrected

**Review by ClareJitu — CHANGES_REQUESTED** [review]
Screenshot from 2022-08-03 18-45-02
The button height should be adjusted
Screenshot from 2022-08-03 18-45-50
The 'I4GxZuri' in the footer should not be black

**Review by spykelionel — APPROVED** [review]
Thanks 👍

**Pull request merged**
