### PR TITLE
Fn products page

### PR DESCRIPTION
**Pull request by Codeyenum**

### CODE REVIEW

**Comment by ClareJitu** [comment]
No product page seen, just landing page

**Comment by spykelionel** [comment]
Check this
https://deploy-preview-62--auth-wiki.netlify.app/product/product

**Comment by ClareJitu** [comment]
Screenshot 2022-07-30 at 18-51-58 Product
The 'learn more' should be in white. Nice work!.
Please the landing page corrections should take effect in these designs

**Comment by spykelionel** [comment]
check this
https://deploy-preview-59--auth-wiki.netlify.app/

**Comment by ClareJitu** [comment]
The latest preview you sent for the product page shows landing page

**Review by spykelionel — CHANGES_REQUESTED** [review]
Please follow the new structure of folders in a repo . follow the link

[New folder stucture](https://i4gxzuriprojectphase.slack.com/archives/C03PVTPM19R/p1659199995009159?thread_ts=1658401079.432289&cid=C03PVTPM19R)

**Comment by Codeyenum** [comment]
Folder Restructuring done

**Comment by Codeyenum** [comment]
Logo redirect done

**Comment by spykelionel** [comment]
Duplicate pull request. Check #46 #74

**Comment by Codeyenum** [comment]
product and products-page are separate pages. It isn't a duplicate

**Comment by spykelionel** [comment]
> product and products-page are separate pages. It isn't a duplicate

Please can you explain more? What's their differences?

**Comment by spykelionel** [comment]
Then you should have named it as product-search

You can do that now. Thanks

**Review by spykelionel — APPROVED** [review]
Okay 👍

**Review by spykelionel — CHANGES_REQUESTED** [review]
Change it to product-search

**Pull request closed without merging**
