### PR TITLE
SignUp page

### PR DESCRIPTION
**Pull request by Victorious-Toluwalope**

### CODE REVIEW

**Review by spykelionel — CHANGES_REQUESTED** [review]
The the form should be centered on the page
changes

**Review by spykelionel — COMMENTED** [review]
Good work there.

**Comment by spykelionel** [comment]
Also, please follow branch naming rules. fn_ for frontend, bn_ for backend. Thanks. Keep up the good work.

**Comment by Victorious-Toluwalope** [comment]
Thank you for the feedback. I will certainly effect the changes now.

**Pull request closed without merging**
