### PR TITLE
Signup page - MAIN

### PR DESCRIPTION
**Pull request by Victorious-Toluwalope**

### CODE REVIEW

**Comment by ClareJitu** [comment]
center alignment is okay

**Review by spykelionel — CHANGES_REQUESTED** [review]
Great work...

Please check the branch test-signup-preview.

It contains a structure of pages, how the new pages will come in as of now. You can cherry pick or copy your css for center alignment to that branch. Now, you can submit a PR directly from the branch(test-signup-preview). 

Thanks. You are doing well

**Review by spykelionel — APPROVED** [review]
Good

**Review by ClareJitu — CHANGES_REQUESTED** [review]
Screenshot from 2022-08-03 18-42-03
The 'Log in' should be in bold
Also, the I4g down should have a smaller font weight

**Comment by spykelionel** [comment]
> 

@ClareJitu Check recent changes

**Review by ClareJitu — COMMENTED** [review]
This is the sign up page from our design. Adjust the location of the 'Already have an account' text
Screenshot from 2022-08-04 13-05-37
.

**Comment by spykelionel** [comment]
Thanks. Check again pls

**Comment by ClareJitu** [comment]
Lionel, I just checked, it hasn't been updated?

**Pull request merged**
